sonar.projectKey=FlossWare_scraping
sonar.projectName=FlossWare scraping
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.10,3.11,3.12,3.13,3.14
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/dist/**
sonar.test.inclusions=tests/**/*.py
